# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-21 00:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='album name', max_length=32, null=True)),
                ('release_date', models.DateField(auto_now=True, help_text='date this album was released')),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='name of artist', max_length=32, null=True)),
                ('website', models.URLField(blank=True, help_text='artists website', null=True)),
                ('instagram', models.CharField(blank=True, help_text='Instagram handle', max_length=32, null=True)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of contact', max_length=32)),
                ('description', models.CharField(blank=True, help_text='describe this genre', max_length=255, null=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='name of song', max_length=32, null=True)),
                ('track', models.IntegerField(help_text='tack number on album')),
                ('duration', models.CharField(blank=True, help_text='length of song', max_length=32, null=True)),
                ('album', models.ForeignKey(help_text='album this song is on', on_delete=django.db.models.deletion.CASCADE, to='catalog.Album')),
            ],
            options={
                'db_table': 'songs',
            },
        ),
        migrations.AddField(
            model_name='favorite',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Song'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(help_text='artist for this album', on_delete=django.db.models.deletion.CASCADE, to='catalog.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(help_text='genre for this album', on_delete=django.db.models.deletion.CASCADE, to='catalog.Genre'),
        ),
    ]
